title: 牵着蜗牛去长大
description: 牵着蜗牛去长大：养育笔记
lang: zh-CN
timezone: Asia/Shanghai
url: https://twoeggdu.github.io
baseurl: ""
theme: minima
markdown: kramdown

header_pages:
  - docs.md
  - notes.md

collections:
  notes:
    output: true
    permalink: /notes/:name/

defaults:
  - scope:
      path: ""
      type: notes
    values:
      layout: page
